# Generated by Django 5.1.2 on 2024-10-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicatin_year',
            new_name='publication_year',
        ),
    ]
