# Generated by Django 5.0.8 on 2024-09-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
